[package]
name = "audit-notes"
version = "0.0.1"
edition = "2024"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }

[lints.clippy]
complexity = "warn"
nursery = "warn"
pedantic = "warn"
style = "warn"
